### PR TITLE
Adds Localization

### PR DESCRIPTION
**Pull request by maybenikhil**
Adds Localization, using i18n-static for mkdocs. This will work fine for the final version's deploy, but some images won't load properly using the current docker-compose solution. I think this is fine for testing/for now but it will need to be specified once there are localization-specific images.

### CODE REVIEW

**Comment by maybenikhil** [comment]
latest update changes some behaviors - now images that are originally in the folder will load, added images require a docker reload for them to work with localized versions. Would like to get merged in pretty fast so I don't have to manually rename a ton of files

**Comment by deadbytefpv** [comment]
Seems to work on my end.
That initial docker build is failing though, and I have to exclude the python script from run, and instead run it manually.

**Comment by ultrabug** [comment]
Hello I've been pinged by @jurgelenas here because there seems to be a problem which I'm not sure I know enough of your workflow to try and reproduce.

I'd be glad to help you fix this if anyone could spare a quick introduction or howto reproduce simply?

Cheers

**Comment by maybenikhil** [comment]
Yep! When I used images, they would not work at all in the localized folders. I think this may be an artifact of our internal linking issues (we have to use ../ for all of our links). This is built using mike versioning which I have not seen any other localized website use. Thank you!

**Comment by ultrabug** [comment]
@maybenikhil hi; so I tried running the docs locally using the docker compose but I see no problem, images are displayed okay

So I'm sorry but I need to reiterate my primary question because if I don't see it, I can't help fixing it :(

> I'd be glad to help you fix this if anyone could spare a quick introduction or howto reproduce simply?

**Comment by maybenikhil** [comment]
Did you check in multiple localizations? Because my issue only appeared in the localizations, not the base website. I also could have had something configured wrong locally

**Comment by ultrabug** [comment]
I think I did yes @maybenikhil ; could you share a URL path to make sure?

**Comment by maybenikhil** [comment]
I'll test again on my local build and see what happens, later today/this week and if i can reproduce the issue then I will like a url with it

**Pull request closed without merging**
