### PR TITLE
Updated ELRSv2 lua link; WiFi Connectivity section.

### PR DESCRIPTION
**Pull request by deadbytefpv**
Please update a few outdated images on the page.
I do not have a BW Radio that I can use to acquire screengrabs from.
Feel free to add any other changes I missed.

Thanks!

### CODE REVIEW

**Comment by deadbytefpv** [comment]
I did a few updates on the TX Updating Method via WiFi, particularly with regards to the ExpressLRS lua script.

I also used admonitions (https://squidfunk.github.io/mkdocs-material/reference/admonitions/) to catch users' attention better for any gotchas .

**Comment by maybenikhil** [comment]
i'm assuming you want someone to get the images? If so, could you list the filenames. I know @CapnBry has a 128x64 radio

**Comment by deadbytefpv** [comment]
> i'm assuming you want someone to get the images? If so, could you list the filenames. I know @CapnBry has a 128x64 radio

I wish to have the screengrabs updated, possibly all images under ./images/lua
and a few under ./images (lua1.jpg, lua2.jpg; both showing the older lua script under tools page).

Thanks!

**Comment by CapnBry** [comment]
You can get screeshots more easily from Companion by just running the script from the simulator. Just copy elrsV2.lua to the sd card's TOOLS directory, and the "mockup" directory from our repo as well. More verbose directions are in [the README](https://github.com/ExpressLRS/ExpressLRS/tree/master/src/lua/mockup)

 (Although wait until my Lua PR is merged for 2.0 because it fills out the VTX Admin screen too if you want that)

**Comment by deadbytefpv** [comment]
Lua v2 Screengrabs updated.

Please review and let me know of any needed updates.

Thanks!

**Comment by CapnBry** [comment]
This should probably not point directly to the elrsV2.lua in 2.0-RC1 tag because that has a bug (and possibly more). I think it should just point to master's version until 2.0 release and then we can point to the 2.0 release Lua.

**Comment by deadbytefpv** [comment]
> This should probably not point directly to the elrsV2.lua in 2.0-RC1 tag because that has a bug (and possibly more). I think it should just point to master's version until 2.0 release and then we can point to the 2.0 release Lua.

Gotcha. Will revert that last commit.

**Pull request merged**
