### PR TITLE
Sortable table and ranking style long range board

### PR DESCRIPTION
**Pull request by StonedDawg**
change the long range leaderboard to a ranking leader board. this way, more people can join the range competition and see their position according to their own "criteria".

### CODE REVIEW

**Comment by jurgelenas** [comment]
Looks cool!

**Review by jurgelenas — APPROVED** [review]

**Comment by maybenikhil** [comment]
I'd rather it be 900M and 2.4 instead of power levels, I think it's a bit more simple

**Comment by StonedDawg** [comment]
@maybenikhil yeah it's a bit of a hard decision... if we split by something else thats not ``power``, it might make the record that would end up on top would be those with bigger power.

**Comment by maybenikhil** [comment]
That's fair

**Comment by deadbytefpv** [comment]
Can we maybe add a "filter" like users can just see "900MHz" or just "2.4GHz"

or for packet rates as well..

**Comment by StonedDawg** [comment]
@deadbytefpv yeah I get what you mean.... I want that as well, but I think I would do that in another PR. I need to learn which plugin is best to handle most of our tables without messing too much with javascript (area where I haven't learn much here 😁)

**Comment by maybenikhil** [comment]
I'll merge it and delete the wiki page :)

**Pull request merged**
