### PR TITLE
Add RCVR_INVERT_TX documentation

### PR DESCRIPTION
**Pull request by CapnBry**
Add documentation for the RCVR_INVERT_TX option, to use am SBUS pad on a FC. NOT SBUS PROTOCOL, inverted CRSF!!

* Moves USE_UART2 to obsolete_defines.
* Rewrites quick start's "Firmware Options" page to just contain essential settings

### CODE REVIEW

**Comment by maybenikhil** [comment]
Could this also go on # firmware options in the quick start guide - also do you think it should be accompanied by a picture of wiring.

**Comment by CapnBry** [comment]
I can update the firmware options in the quickstart guide with a half sentence about it. We definitely do not want to start putting the same documentation twice everywhere though, because the maintenance is difficult where one section will get updated and the other will not.

**Comment by CapnBry** [comment]
Done! I feel like we should really remove the majority of the options from the Firmware Options page though and replace the ones we keep with a single sentence instead of a copypaste from the other page. Things like `FEATURE_OPENTX_SYNC`  and `TLM_REPORT_INTERVAL_MS` aren't quick start applicable. 

I'm also for removing the "-D" prefix on all the user_defines page since the Configurator doesn't have the -D and it could be confusing. We can just put a bit at the top in the Defines 101 that says they need to start with -D. Also removing the bit about "we recommend reading this page **in its entirety** before first flashing" because we do not recommend that at all do we?

**Comment by maybenikhil** [comment]
Agreed. Would you like to bring that into this PR or another?

**Comment by CapnBry** [comment]
I can do it in this one if that's ok, I mean multiple things in one PR and all that but it's not like this is code, that the resulting text makes sense is all that is needed.

**Comment by maybenikhil** [comment]
Yep Im absolutely fine with it being done in here

**Comment by CapnBry** [comment]
Alright I'll have it for you later today.

**Comment by CapnBry** [comment]
I've slimmed down the list of firmware-options to only those items the user would probably change on their first setup or might consider turning off, along with simpler descriptions for them on that page.

I've filled out a couple of the user_defines as well with some extra information as well when I thought the descriptions from the quick start page would also be helpful in the detail page.

**Pull request merged**
