### PR TITLE
New Quickstart Structure

### PR DESCRIPTION
**Pull request by deadbytefpv**
This structure proposes having per-device flashing guide.

This would work as how it's done via the Supported Hardware page in the wiki.

The aim is to keep users in as much few pages as possible without having to scroll too long to get the needed information.

The pages has been structured so that the steps are more logical or easy to follow. This was patterned to how I do my flashing or updates.

Steps are as follows:
Download Configurator
Set firmware Options (I try to first explain what the options are for, so when users are actually ready to flash, they know which options to select.)
Prepare Radio (OpenTX, Lua Script download, etc)
Flashing the TX Module (separated to each device)
Flashing bootloaders to receivers (mostly r9)
Preparing for Passthrough Flashing (wiring to FC, betaflight/inav configs)
Preparing for STLink Flashing (Wiring up receivers to STLink v2s, downloading necessary apps, etc)
Flashing the firmware (separated to each receiver "family")
Binding
Pre-first-flight Checks (OSD, Telemetry, RSSI dbm check)

Note that I have only put some content on some pages and they still need further refinement.

### CODE REVIEW

**Comment by jurgelenas** [comment]
I really like this new structure :)

**Comment by deadbytefpv** [comment]
Here's what's left to do on this branch:
1. HM900 stuff
2. NamimnoRC stuff
3. Pre-first Flight Checks (OSD, Lua, Bench test)
4. Navigation Structure (Sidebar and page Titles)

I will try to get the HM and Pre-first Flight Checks page done before Friday.. But I'll be needing some help on those other points, and overall page checks.. 

Thanks!

**Comment by deadbytefpv** [comment]
Progress 4 Update
1. Added HM900 Content
2. Added Pre-first Flight Setup Content
3. Navigation menu Update

I haven't done much proofreading yet, but feel free to merge or let me know of any edits you want me to do.. 

Thanks!

**Comment by jurgelenas** [comment]
> Progress 4 Update
> 
> 1. Added HM900 Content
> 2. Added Pre-first Flight Setup Content
> 3. Navigation menu Update
> 
> I haven't done much proofreading yet, but feel free to merge or let me know of any edits you want me to do..
> 
> Thanks!

I suggest trying https://www.grammarly.com/ for automated proofreading :) trust me, it’s good!

**Comment by deadbytefpv** [comment]
> > Progress 4 Update
> > 
> > 1. Added HM900 Content
> > 2. Added Pre-first Flight Setup Content
> > 3. Navigation menu Update
> > 
> > I haven't done much proofreading yet, but feel free to merge or let me know of any edits you want me to do..
> > Thanks!
> 
> I suggest trying https://www.grammarly.com/ for automated proofreading :) trust me, it’s good!

Thank you for the suggestion! Already installed :)

**Comment by jurgelenas** [comment]
> > > Progress 4 Update
> > > 
> > > 1. Added HM900 Content
> > > 2. Added Pre-first Flight Setup Content
> > > 3. Navigation menu Update
> > > 
> > > I haven't done much proofreading yet, but feel free to merge or let me know of any edits you want me to do..
> > > Thanks!
> > 
> > 
> > I suggest trying https://www.grammarly.com/ for automated proofreading :) trust me, it’s good!
> 
> Thank you for the suggestion! Already installed :)

Awesome!

**Comment by maybenikhil** [comment]
TODO BEFORE MERGE:
Provide a better getting started page for this so users have a bit more understanding of the layout
Check all (important) wiki pages are merged over
Add people page? - give the devs some credit!
Get SIYI work done

**Pull request merged**
