### PR TITLE
Update long-range.md

### PR DESCRIPTION
**Pull request by molokaiboy**
Mahalo to all the ELRS Devs

### CODE REVIEW

**Comment by StonedDawg** [comment]
nice flight.... but.. i'm wondering what happen to 6,7,8...19km? ;D

**Comment by molokaiboy** [comment]
Thank you. Nothing eventful, I can make a longer edit to include it and
resubmit it after work this evening.

Mahalo,

Les

**Comment by molokaiboy** [comment]
I edited the doc and replaced with lonerger video, see comment in update

Mahalo,

Les

**Review by StonedDawg — APPROVED** [review]
nice! island crossing! 🥰

**Comment by molokaiboy** [comment]
Thank-you! I'm hoping to push the 2.4g gear like I've been doing with 915.
It's such an awesome feeling to push distance on low power.
I'm hoping to see if I can pass my 40.7km flight I did with 915 @ 10mw.

Mahalo,

Les

**Comment by maybenikhil** [comment]
setting record after record!

**Review by maybenikhil — APPROVED** [review]

**Pull request merged**
