### PR TITLE
Add SysId configuration,

### PR DESCRIPTION
**Pull request by LupusTheCanine**
Add SysId configuration, requires ExpressLRS/ExpressLRS#2891 (assumes live reconfiguration of sysID)

### CODE REVIEW

**Review by wvarty — APPROVED** [review]

**Comment by wvarty** [comment]
@LupusTheCanine this PR looks like it needs some words added to the `.wordlist.txt` file before it will pass the spellcheck job. Check the logs for details.

**Review by wvarty — CHANGES_REQUESTED** [review]
Make spellcheck happy.

**Comment by maybenikhil** [comment]
waiting on https://github.com/ExpressLRS/ExpressLRS/pull/2964 to be merged (assuming i'm not being braindead)

**Comment by LupusTheCanine** [comment]
> waiting on [ExpressLRS/ExpressLRS#2964](https://github.com/ExpressLRS/ExpressLRS/pull/2964) to be merged (assuming i'm not being braindead)

Yes, unfortunately I didn't have much time to work on that, the only difference is that right now an RX serial reinitialization (reboot?) is required.

**Comment by maybenikhil** [comment]
would it be accurate to then add another line saying to reboot the RX again?

**Comment by wvarty** [comment]
> waiting on [ExpressLRS/ExpressLRS#2964](https://github.com/ExpressLRS/ExpressLRS/pull/2964) to be merged (assuming i'm not being braindead)

That PR is an additional enhancement on the functionality. This can and should be merged without waiting on that PR. The feature is already there is 3.5.0

**Review by wvarty — APPROVED** [review]

**Pull request merged**
