### PR TITLE
Adds Warning for Lua Update while Armed

### PR DESCRIPTION
**Pull request by deadbytefpv**

### CODE REVIEW

**Comment by CapnBry** [comment]
Can you change the formatting to:
```
!!! attention ""
Text goes here
```

This makes the orange warning section for it instead of just being bold. Remove the bold formatting and WARNING too I think after that.

Can you also add to the "Packet Rate" section there?
> **NEVER** change the packet rate while flying as this **FORCES A DISCONNECT** between the TX and RX.

**Comment by deadbytefpv** [comment]
I contemplated using admonitions for the text as I feel like the admonition texts are smaller than I thought these warnings should be.. 

This last commit used the Warning admonition, along with an icon and WARNING title.

Also added the line regarding Packet Rate.

Thanks @CapnBry

**Comment by CapnBry** [comment]
Nice!

You might want to say why you shouldn't change the switch mode when connected on that new change though. I don't like when something says "you shouldn't do X" and then has no explanation. The explanation is that you _can't_ change it when connected. How about something like this?
> The Switch Mode can only be changed when not connected to a receiver. The top right corner of the lua script will show a `-` if you're not connected.

**Comment by deadbytefpv** [comment]
Thanks @CapnBry 

I have updated the Hot Tip for Switch Mode as per your suggestion.

**Comment by CapnBry** [comment]
Love it! Do I get to volt on approvals for this repo? Let's find out!

**Review by CapnBry — APPROVED** [review]

**Pull request merged**
