### PR TITLE
Passthrough Method Reminder

### PR DESCRIPTION
**Pull request by deadbytefpv**
Added the clause for making sure the FC Configurator apps are closed, with the addition of unplugging the USB.

### CODE REVIEW

**Comment by maybenikhil** [comment]
Possible phrasing change - you should not be connected to Betaflight/INAV configurator (instead of you do not need to be connected to)

**Comment by deadbytefpv** [comment]
> Possible phrasing change - you should not be connected to Betaflight/INAV configurator (instead of you do not need to be connected to)

What about this: You don't need to be connected to Betaflight or INAV Configurator during this step. Disconnect from your FC Configurator, close it and unplug the USB to refresh the connection.

**Comment by maybenikhil** [comment]
> What about this: You don't need to be connected to Betaflight or INAV Configurator during this step. Disconnect from your FC Configurator, close it and unplug the USB to refresh the connection.

I think this comes into the same issue of using don't. Don't generally to me means you can be, but it's not required. I think a combination would be:

For the following steps, you should not be connected to Betaflight or Inav Configurator. Disconnect your FC Configure, close it, and unplug-replug the USB to refresh the connection.

**Comment by deadbytefpv** [comment]
> > What about this: You don't need to be connected to Betaflight or INAV Configurator during this step. Disconnect from your FC Configurator, close it and unplug the USB to refresh the connection.
> 
> I think this comes into the same issue of using don't. Don't generally to me means you can be, but it's not required. I think a combination would be:
> 
> For the following steps, you should not be connected to Betaflight or Inav Configurator. Disconnect your FC Configure, close it, and unplug-replug the USB to refresh the connection.

Got ya. The "you don't need" sounds weak too, imho..

**Review by maybenikhil — APPROVED** [review]

**Pull request merged**
